### ISSUE TITLE
convert the data to MultiWOZ2.1 format

### ISSUE THREAD

**Issue by Valdemar-Yu** [armandstrickernlp/chitchat-as-interference#1]
I am a user of the project, and I have some questions regarding certain aspects of it. I would appreciate it if you could help clarify these for me.

My questions are:

I encountered some issues while converting the data to MultiWOZ2.1 format.I dont know how to format Multiwoz to one single .json with all the annotated dialogues.Then, I noticed in the data/prep_simpletod_data.py, there need interference_data/test.json, i dont know what it is. Wheather MultiWOZ convert to these three .json (data.json , test.json , val.json)

Thank you very much for your time and assistance. I look forward to your response.

**Comment by armandstrickernlp** [comment]
Hi, 
- for converting to the right format, look at the bottom of this page [here](https://github.com/budzianowski/multiwoz/tree/master/data/MultiWOZ_2.2). 
- the `interference_data/` directory is generated after the interference generation step. This is done in `merge_interference_to_mwoz.py`. 
-  But don't worry, I'll add the prepped data with the interferences soon (by the end of the week hopefully).

**Comment by Valdemar-Yu** [comment]
Thank you！I will try it later. Your reply is really vital for me.

**Comment by armandstrickernlp** [comment]
The mwoz dialogues with the added chitchat interferences are now available.
