### ISSUE TITLE
bleu doesnt exist

### ISSUE THREAD

**Issue by Valdemar-Yu** [armandstrickernlp/chitchat-as-interference#2]
sorry，I meet a new problem.
<img width="966" alt="Snipaste_2024-04-29_00-01-51" src="https://github.com/armandstrickernlp/chitchat-as-interference/assets/129027315/16998b85-41c1-4ed5-9e8c-6fddfae7d265">
When I try to evaluate my checkpoints,it broken.If you tell me how to fix it,I will be really appreciate to you.

**Comment by armandstrickernlp** [comment]
I think this arises when you evaluate *offline*. Take a look at this issue for bleu in the evaluate library: https://github.com/huggingface/evaluate/issues/391
